/*
 * Tatum API Reference
 *
 * # Welcome to the Tatum API Reference!  ## What is Tatum?  Tatum offers a flexible framework to build, run, and scale blockchain apps fast. To learn more about the Tatum blockchain development framework, visit [our website](https://tatum.io/framework).  The Tatum API features powerful endpoints that simplify a complex blockchain into single API requests. Code for all supported blockchains using unified API calls.  ## Need help?  To chat with other developers, get help from the Support team, and engage with the thriving Tatum community, join  our [Discord server](https://discord.com/invite/tatum). For more information about how to work with Tatum, review the [online documentation](https://docs.tatum.io/).  ## About this API Reference  The Tatum API Reference is based on OpenAPI Specification v3.1.0 with a few [vendor extensions](https://github.com/Redocly/redoc/blob/master/docs/redoc-vendor-extensions.md) applied.  # Authentication  When using the Tatum API, you authenticate yourself with an **API key**. <SecurityDefinitions /> 
 *
 * The version of the OpenAPI document: 3.17.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Tatum.CSharp.Solana.Core.Client.FileParameter;
using OpenAPIDateConverter = Tatum.CSharp.Solana.Core.Client.OpenAPIDateConverter;

namespace Tatum.CSharp.Solana.Core.Model
{
    /// <summary>
    /// Options for sending and waiting for a transaction
    /// </summary>
    [DataContract(Name = "SolanaBroadcastConfirmOptions")]
    public partial class SolanaBroadcastConfirmOptions : IEquatable<SolanaBroadcastConfirmOptions>, IValidatableObject
    {
        /// <summary>
        /// Commitment to waiting for transaction confirmation
        /// </summary>
        /// <value>Commitment to waiting for transaction confirmation</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum CommitmentEnum
        {
            /// <summary>
            /// Enum Confirmed for value: confirmed
            /// </summary>
            [EnumMember(Value = "confirmed")]
            Confirmed = 1,

            /// <summary>
            /// Enum Finalized for value: finalized
            /// </summary>
            [EnumMember(Value = "finalized")]
            Finalized = 2

        }


        /// <summary>
        /// Commitment to waiting for transaction confirmation
        /// </summary>
        /// <value>Commitment to waiting for transaction confirmation</value>
        [DataMember(Name = "commitment", EmitDefaultValue = false)]
        public CommitmentEnum? Commitment { get; set; }

        /// <summary>
        /// Preflight Commitment.
        /// </summary>
        /// <value>Preflight Commitment.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum PreflightCommitmentEnum
        {
            /// <summary>
            /// Enum Confirmed for value: confirmed
            /// </summary>
            [EnumMember(Value = "confirmed")]
            Confirmed = 1,

            /// <summary>
            /// Enum Finalized for value: finalized
            /// </summary>
            [EnumMember(Value = "finalized")]
            Finalized = 2,

            /// <summary>
            /// Enum Processed for value: processed
            /// </summary>
            [EnumMember(Value = "processed")]
            Processed = 3,

            /// <summary>
            /// Enum Recent for value: recent
            /// </summary>
            [EnumMember(Value = "recent")]
            Recent = 4,

            /// <summary>
            /// Enum Single for value: single
            /// </summary>
            [EnumMember(Value = "single")]
            Single = 5,

            /// <summary>
            /// Enum SingleGossip for value: singleGossip
            /// </summary>
            [EnumMember(Value = "singleGossip")]
            SingleGossip = 6,

            /// <summary>
            /// Enum Max for value: max
            /// </summary>
            [EnumMember(Value = "max")]
            Max = 7

        }


        /// <summary>
        /// Preflight Commitment.
        /// </summary>
        /// <value>Preflight Commitment.</value>
        [DataMember(Name = "preflightCommitment", EmitDefaultValue = false)]
        public PreflightCommitmentEnum? PreflightCommitment { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="SolanaBroadcastConfirmOptions" /> class.
        /// </summary>
        /// <param name="commitment">Commitment to waiting for transaction confirmation.</param>
        /// <param name="preflightCommitment">Preflight Commitment..</param>
        public SolanaBroadcastConfirmOptions(CommitmentEnum? commitment = default(CommitmentEnum?), PreflightCommitmentEnum? preflightCommitment = default(PreflightCommitmentEnum?))
        {
            this.Commitment = commitment;
            this.PreflightCommitment = preflightCommitment;
        }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SolanaBroadcastConfirmOptions {\n");
            sb.Append("  Commitment: ").Append(Commitment).Append("\n");
            sb.Append("  PreflightCommitment: ").Append(PreflightCommitment).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SolanaBroadcastConfirmOptions);
        }

        /// <summary>
        /// Returns true if SolanaBroadcastConfirmOptions instances are equal
        /// </summary>
        /// <param name="input">Instance of SolanaBroadcastConfirmOptions to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SolanaBroadcastConfirmOptions input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Commitment == input.Commitment ||
                    this.Commitment.Equals(input.Commitment)
                ) && 
                (
                    this.PreflightCommitment == input.PreflightCommitment ||
                    this.PreflightCommitment.Equals(input.PreflightCommitment)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Commitment.GetHashCode();
                hashCode = (hashCode * 59) + this.PreflightCommitment.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
