name: Deploy RC Package

on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string
      version:
        required: true
        type: string
        
env:
  PROJECT_PATH: ./${{ inputs.package }}/Tatum.CSharp.${{ inputs.package }}/Tatum.CSharp.${{ inputs.package }}.csproj
  PACKAGE_SOURCE: https://nuget.pkg.github.com/tatumio/index.json

jobs:
  preparePackage:
    name: ${{ inputs.package }} - Build & Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Add package source
        run: dotnet nuget add source --username tatumio --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "${{ env.PACKAGE_SOURCE }}"
      - name: Add version number to 'Tatum_CSharp_SDK' string in Configuration.cs 
        run: |
          sed -i "s,Tatum_SDK_CSharp,Tatum_SDK_CSharp_${{ inputs.package }}/${{ inputs.version }},g" ./${{ inputs.package }}/Tatum.CSharp.${{ inputs.package }}.Core/Client/Configuration.cs
          grep -i "Tatum_SDK_CSharp" ./${{ inputs.package }}/Tatum.CSharp.${{ inputs.package }}.Core/Client/Configuration.cs     
      - name: ${{ inputs.package }} - Restore dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }}
      - name: ${{ inputs.package }} - Build
        run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release
      - name: ${{ inputs.package }} - Pack
        run: dotnet pack ${{ env.PROJECT_PATH }} --no-build --no-restore --configuration Release /p:Version=${{ inputs.version }} --output .
      - name: ${{ inputs.package }} - Push to Github Packages
        run: dotnet nuget push "./Tatum.CSharp.${{ inputs.package }}.${{ inputs.version }}.nupkg" --skip-duplicate --api-key ${{ secrets.ACTIONS_PACKAGE_SOURCE_PAT }} --source "github"
