name: Tatum.CSharp Dev Packages
run-name: ${{ inputs.source }}

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:
    inputs:
      source:
        description: 'Source of event'
        required: false
        default: ''

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  Build_Version:
    name: Get Version
    uses: ./.github/workflows/calculateBuildVersion.yml
  
  Core_Pack_RC:
    name: Core - Pack Local
    uses: ./.github/workflows/deployReleaseCandidatePackage.yml
    with:
      name: Core
      version: ${{ needs.Build_Version.outputs.version }}
    secrets: inherit
    needs: Build_Version
  
  Release_L1_Chains:
    strategy:
      matrix:
        arrays: [
          { "chain": "Evm.Local", "dependsOn": "Core" },
          { "chain": "Bitcoin.Local", "dependsOn": "Core" }
        ]
    name: ${{ matrix.chain }} - Deploy Chain Dev Packages
    uses: ./.github/workflows/deployReleaseCandidatePackage.yml
    with:
      dependsOn: ${{ matrix.arrays.dependsOn }}
      chain: ${{ matrix.arrays.chain }}
      version: ${{ needs.Build_Version.outputs.version }}
    secrets: inherit
    needs: [ Build_Version, Core_Pack_RC ]
  
  Release_L2_Chains:
    strategy:
      matrix:
        arrays: [
          { "chain": "Evm", "dependsOn": "Evm.Local" },
          { "chain": "Polygon", "dependsOn": "Evm.Local" },
          { "chain": "Nft", "dependsOn": "Evm.Local" },
          { "chain": "BSC", "dependsOn": "Evm.Local" },
          { "chain": "Bitcoin", "dependsOn": "Bitcoin.Local" },
        ]
    name: ${{ matrix.arrays.chain }} - Deploy Chain Dev Packages
    uses: ./.github/workflows/deployReleaseCandidatePackage.yml
    with:
      dependsOn: ${{ matrix.arrays.dependsOn }}
      chain: ${{ matrix.arrays.chain }}
      version: ${{ needs.Build_Version.outputs.version }}
    secrets: inherit
    needs: [ Build_Version, Release_L2_Chains ]
