name: Tatum.CSharp Dev Package
run-name: ${{ inputs.source }}

on:
  workflow_call:
    inputs:
      chain:
        description: 'Chain to release'
        required: true
        type: string
      version:
        description: 'Package Version'
        required: true
        type: string
      dependsOn:
        description: 'Package to depend on'
        required: false
        type: string

jobs:
  Dependency_Pack_RC:
    name: ${{ inputs.dependsOn }} - Pack Local
    uses: ./.github/workflows/deployReleaseCandidatePackage.yml
    with:
      name: ${{ inputs.dependsOn }}
      version: ${{ inputs.version }}
      dependsOn: Core
    secrets: inherit
  
  Pack_RC:
    name: ${{ inputs.chain }} - Pack
    uses: ./.github/workflows/deployReleaseCandidatePackage.yml
    with:
      name: ${{ inputs.chain }}
      version: ${{ inputs.version }}
      dependsOn: ${{ inputs.dependsOn }}
    secrets: inherit
    needs: [Dependency_Pack_RC]
    
#  Integration_Tests:
#    name: ${{ inputs.chain }} - Test
#    uses: ./.github/workflows/integrationTests.yml
#    with:
#      name: ${{ inputs.chain }}
#      version: ${{ inputs.version }}
#    secrets: inherit
#    needs: [Pack_RC]
