name: Tatum.CSharp Dev Package
run-name: ${{ inputs.source }}

on:
  workflow_call:
    inputs:
      dependency:
        description: 'Package that chains depend on'
        required: false
        type: string
      chains:
        description: 'Chains to release'
        required: true
        type: string
      version:
        description: 'Package Version'
        required: true
        type: string

jobs:
  Dependency_Pack_RC:
    name: ${{ inputs.dependency }} - Pack Local
    uses: ./.github/workflows/deployReleaseCandidatePackage.yml
    with:
      name: ${{ inputs.dependency }}
      version: ${{ inputs.version }}
      dependsOn: Core
    secrets: inherit
  
  Parse_chains:
    name: Parse Chains
    runs-on: ubuntu-latest
    outputs:
      output1: ${{steps.chains.outputs.chainArray}}
    steps:
      - name: Parse Chains to a variable
        id: chains
        shell: bash
        run: echo "chainArray=${{ inputs.chains }}" >> $GITHUB_OUTPUT
      - name: Parse Chains to a variable
        id: chains2
        shell: bash
        run: echo $chainArray
  
  Pack_RC:
    strategy:
      matrix:
        chain: ${{ needs.Parse_chains.outputs.chainArray }}
    name: ${{ matrix.chain }} - Pack
    uses: ./.github/workflows/deployReleaseCandidatePackage.yml
    with:
      name: ${{ matrix.chain }}
      version: ${{ inputs.version }}
      dependsOn: ${{ inputs.dependency }}
    secrets: inherit
    needs: [Parse_chains, Dependency_Pack_RC]