name: Tatum.CSharp Dev Packages
run-name: ${{ inputs.source }}

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:
    inputs:
      source:
        description: 'Source of event'
        required: false
        default: ''

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  Build_Version:
    name: Get Version
    uses: ./.github/workflows/calculateBuildVersion.yml

  Release_Packages:
    strategy:
      matrix:
        package: [
          Ethereum,
          Polygon,
          Nft,
          FungibleTokens,
          BlockchainFees,
          Bsc,
          Harmony,
          Bitcoin,
          Solana
        ]
    name: ${{ matrix.package }} - Deploy Dev Package
    uses: ./.github/workflows/deployReleaseCandidatePackage.yml
    with:
      package: ${{ matrix.package }}
      version: ${{ needs.Build_Version.outputs.version }}
    secrets: inherit
    needs: Build_Version
