name: Tatum.CSharp Dev Packages
run-name: ${{ inputs.source }}

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:
    inputs:
      source:
        description: 'Source of event'
        required: false
        default: ''

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  Build_Version:
    name: Get Version
    uses: ./.github/workflows/calculateBuildVersion.yml
  
  Core_Pack_RC:
    name: Core - Pack Local
    uses: ./.github/workflows/deployReleaseCandidatePackage.yml
    with:
      name: Core
      version: ${{ needs.Build_Version.outputs.version }}
    secrets: inherit
    needs: Build_Version
  
  Release_Chains:
    strategy:
      matrix:
        arrays: [
          { dependency: "Evm.Local", chains: [Ethereum, Polygon, Nft] },
          { dependency: "Bitcoin.Local", chains: [Bitcoin] },
        ]
    name: ${{ matrix.arrays.chains }} - Deploy Chain Dev Packages
    uses: ./.github/workflows/developReleaseSingleChain.yml
    with:
      dependency: ${{ matrix.arrays.dependency }}
      chains: ${{ matrix.arrays.chains }}
      version: ${{ needs.Build_Version.outputs.version }}
    secrets: inherit
    needs: [ Build_Version, Core_Pack_RC ]
