name: Tatum.CSharp Dev Package
run-name: ${{ inputs.source }}

on:
  workflow_call:
    inputs:
      dependency:
        description: 'Package that chains depend on'
        required: false
        type: string
      chains:
        description: 'Chains to release'
        required: true
        type: string
      version:
        description: 'Package Version'
        required: true
        type: string

jobs:
  Dependency_Pack_RC:
    name: ${{ inputs.dependency }} - Pack Local
    uses: ./.github/workflows/deployReleaseCandidatePackage.yml
    with:
      name: ${{ inputs.dependency }}
      version: ${{ inputs.version }}
      dependsOn: Core
    secrets: inherit
  
  Pack_RC:
    strategy:
      matrix:
        chain: ${{ inputs.chains }}
    name: ${{ matrix.chain }} - Pack
    uses: ./.github/workflows/deployReleaseCandidatePackage.yml
    with:
      name: ${{ matrix.chain }}
      version: ${{ inputs.version }}
      dependsOn: ${{ inputs.dependency }}
    secrets: inherit
    needs: [Dependency_Pack_RC]