name: Tatum.CSharp Blockchain packages
run-name: ${{ inputs.source }}

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:
    inputs:
      source:
        description: 'Source of event'
        required: false
        default: ''

jobs:

  Build_Version:
    uses: ./.github/workflows/calculateBuildVersion.yml
  
  ETH_Pack_RC:
    uses: ./.github/workflows/prepareBuildPackage.yml
    with:
      name: Ethereum
      version: ${{ needs.Build_Version.outputs.version }}
    secrets: inherit
    needs: Build_Version
    
  ETH_Integration_Tests:
    uses: ./.github/workflows/integrationTests.yml
    with:
      name: Ethereum
    secrets: inherit
    needs: ETH_Pack_RC
