name: Release Nuget Package

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      version:
        required: true
        type: string
      dependsOn:
        required: false
        type: string

env:
  PROJECT_PATH: ./Tatum.CSharp.${{ inputs.name }}/Tatum.CSharp.${{ inputs.name }}.csproj
  PACKAGE_SOURCE: https://api.nuget.org/v3/index.json
  
jobs:

  preparePackage:
    name: ${{ inputs.name }} - Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Add version number to 'Tatum_CSharp_SDK' string in Configuration.cs
        if: ${{ inputs.name == 'Core' }}
        run: |
          sed -i "s,Tatum_SDK_CSharp,Tatum_SDK_CSharp/v${{ inputs.version }},g" ./Tatum.CSharp.Core/Client/Configuration.cs
          grep -i "Tatum_SDK_CSharp" ./Tatum.CSharp.Core/Client/Configuration.cs    
      - name: Propagate PackageReleaseNotes from the Core package .csproj
        if: ${{ inputs.name != 'Core' }}
        run: |
          sed -i "s/<PackageReleaseNotes>.*<\/PackageReleaseNotes>/<PackageReleaseNotes>$(grep -oPm1 "(?<=<PackageReleaseNotes>)[^<]+" ./Tatum.CSharp.Core/Tatum.CSharp.Core.csproj)<\/PackageReleaseNotes>/g" ${{ env.PROJECT_PATH }}
      - name: ${{ inputs.name }} - Bump Dependencies Version
        if: ${{ inputs.dependsOn != '' }}
        run: dotnet add ${{ env.PROJECT_PATH }} package Tatum.CSharp.${{ inputs.dependsOn }} --no-restore --version ${{ inputs.version }}
      - name: ${{ inputs.name }} - Restore dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }}
      - name: ${{ inputs.name }} - Build
        run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release
      - name: ${{ inputs.name }} - Pack
        run: dotnet pack ${{ env.PROJECT_PATH }} --no-build --no-restore --configuration Release /p:Version=${{ inputs.version }} --output .
      - name: ${{ inputs.name }} - Push to Nuget
        run: dotnet nuget push "./Tatum.CSharp.${{ inputs.name }}.${{ inputs.version }}.nupkg" --skip-duplicate --api-key ${{ secrets.NUGET_PUBLISH_KEY }} --source ${{ env.PACKAGE_SOURCE }}