name: Release PR

on:
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current
        uses: actions/checkout@v3
      - name: Get state current
        run: |
          hash=$(sha1sum CHANGELOG.md | cut -f1 -d' ')
          version=$(<.version)
          echo "pr_version=$version" >> $GITHUB_ENV 
          echo "pr_changelog_hash=$hash" >> $GITHUB_ENV
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Get state main
        run: |
          hash=$(sha1sum CHANGELOG.md | cut -f1 -d' ')
          version=$(<.version)
          echo "main_version=$version" >> $GITHUB_ENV
          echo "main_changelog_hash=$hash" >> $GITHUB_ENV
      - name: Ensure changelog updated
        run: |
          [ "${{ env.pr_changelog_hash }}" = "${{ env.main_changelog_hash }}" ] && echo "Error: no changes in changelog detected for the release" && exit 1 || exit 0  
      - name: Ensure package version updated
        run: |
           [ "${{ env.pr_version }}" = "${{ env.main_version }}" ] && echo "Error: package version not updated" && exit 1 || exit 0