name: Tatum.CSharp Nuget Package
run-name: ${{ inputs.source }}

on:
  workflow_call:
    inputs:
      chain:
        description: 'Chain to release'
        required: true
        type: string
      version:
        description: 'Package Version'
        required: true
        type: string
      dependsOn:
        description: 'Package to depend on'
        required: false
        type: string

jobs:
  Release:
    name: ${{ inputs.chain }} - Release
    uses: ./.github/workflows/releaseNugetPackage.yml
    with:
      name: ${{ inputs.chain }}
      version: ${{ inputs.version }}
      dependsOn: ${{ inputs.dependsOn }}
    secrets: inherit

  Nuget_Wait:
    name: ${{ inputs.chain }} - Nuget package wait
    uses: ./.github/workflows/waitForNuget.yml
    with:
      name: ${{ inputs.chain }}
      version: ${{ inputs.version }}
    secrets: inherit
    needs: Release