name: Tatum.CSharp Nuget Package
run-name: ${{ inputs.source }}

on:
  workflow_call:
    inputs:
      package:
        description: 'Chain to release'
        required: true
        type: string
      version:
        description: 'Package Version'
        required: true
        type: string

jobs:
  Release:
    name: ${{ inputs.package }} - Release
    uses: ./.github/workflows/releaseNugetPackage.yml
    with:
      package: ${{ inputs.package }}
      version: ${{ inputs.version }}
    secrets: inherit

  Nuget_Wait:
    name: ${{ inputs.package }} - Nuget package wait
    uses: ./.github/workflows/waitForNuget.yml
    with:
      package: ${{ inputs.package }}
      version: ${{ inputs.version }}
    secrets: inherit
    needs: Release